### ISSUE TITLE
Read only once by each service

### ISSUE THREAD

**Issue by k3nsei** [sergey-telpuk/nestjs-external-eventbus#4]
Hi,

How to make sure that only one service of its kind will read an event.
For example when I have 3 replicas of mailer service which listens for UserCreated event.
I want to only send one welcome email. How to do that?

**Comment by sergey-telpuk** [comment]
@k3nsei hi, please move to this repo, https://github.com/sergey-telpuk/nestjs-transport-eventbus this is a done lib. 
Answer of your question is the following: 
It depends on an underhood broker. In common cases, only one consumer receives the event from queue.
